name: Deploy to Google Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Deploy Function'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'mcp-travel-planner'
        runtime: 'python311'
        entry_point: 'mcp_travel_planner_http'
        trigger_http: true
        allow_unauthenticated: true
        env_vars: |
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY_SECRET }}
          GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY_SECRET }}
        region: 'us-central1'
        source: '.'
