name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hub
        uses: huggingface/hub-sync@v0.5
        with:
          repo_type: space
          repo_id: ${{ secrets.HF_SPACE_ID }}
          token: ${{ secrets.HF_TOKEN }}
          force: true
