name: Deploy Cloud Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Deploy to Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v3
      with:
        project_id: travel-planner-agent-471801
        region: us-central1
        name: travelagent
        runtime: python39  # or your preferred runtime
        entry_point: main  # your function entry point
        source_dir: ./  # directory containing your function code
        
        # Environment and scaling settings
        environment_variables: |
          ENV=production
          
        # HTTP trigger settings (for HTTP functions)
        # For HTTP functions, you don't need event_trigger_* parameters
        ingress_settings: ALLOW_ALL
        
        # For event-driven functions, use these instead:
        # event_trigger_type: google.cloud.pubsub.topic.v1.messagePublished
        # event_trigger_pubsub_topic: projects/travel-planner-agent-471801/topics/your-topic
        
        # Scaling and resource settings
        min_instance_count: 0
        max_instance_count: 10
        max_instance_request_concurrency: 80
        cpu: "1"
        memory: 256Mi
        service_timeout: 60s
        
        # Service account for the function runtime
        service_account: travelagent-sa@travel-planner-agent-471801.iam.gserviceaccount.com