name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: 'us-central1' # You can change this to your preferred region
  SERVICE_NAME: 'mcp-travel-planner-streamlit'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker to use Google Cloud Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE_NAME}/${SERVICE_NAME}:${{ github.sha }} .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE_NAME}/${SERVICE_NAME}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-run@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          project_id: ${{ env.PROJECT_ID }}
          image: ${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE_NAME}/${SERVICE_NAME}:${{ github.sha }}
          env_vars: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}
          # Add any other necessary Cloud Run configurations here, e.g.,
          # allow-unauthenticated: true
          # port: 8501 # Streamlit's default port